apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netflix-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: netflix
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
