apiVersion: v1
kind: Service
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: netflix
